service:
  title: "Auth service"
  description: "Auth service"
  host: "0.0.0.0"
  port: 8000
  debug: True
  kafka_host: "kafka"
  kafka_port: 9092
  kafka_topic: "faces"
  photo_directory: "./photos"
  acceptable_formats: [".jpg", ".jpeg", ".png"]
  token_ttl: 3600
  db_hostname: "db"
  db_port: 5432
  db_name: postgres
  db_username: postgres
  db_echo: False
  tags_metadata_auth:
    name: "Auth"
    description: "Registration and authentication"
  tags_metadata_check:
    name: "Check"
    description: "Token check"
  tags_metadata_health:
    name: "Health"
    description: "Health check"
  tags_metadata_verify:
    name: "Verify"
    description: "User verification by photo"

jaeger:
  service_name: "auth_service"
  host: "jaeger"
  port: 6831
  logging: True
  sampler_type: "const"
  sampler_param: 1

redis:
  url: "redis://redis:6379"
  db: 0
  decode_responses: True
