service:
  title: "Auth service"
  description: "Сервис авторизации"
  host: "127.0.0.1"
  port: 8000
  debug: True
  tags_metadata_auth:
    name: "Auth"
    description: "Регистрация, аутентификация"
  tags_metadata_check:
    name: "Check"
    description: "Проверка токена"
