apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name}}-photo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: yc-network-hdd
