apiVersion: v1
kind: Service
metadata:
  name: stakrotckii-auth-service-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"
spec:
  selector:
    app.kubernetes.io/name: stakrotckii
    app.kubernetes.io/instance: auth-service-abcxyz
  ports:
    - port: 8000
      targetPort: 8000
