"""Token table deleted

Revision ID: 2babeb13b6f7
Revises: e0ff80a023f3
Create Date: 2024-09-08 12:02:15.132799

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2babeb13b6f7'
down_revision: Union[str, None] = 'e0ff80a023f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'token',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            'user_id', sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            'token', sa.VARCHAR(length=300), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
            name='token_user_id_fkey',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name='token_pkey'),
        sa.UniqueConstraint('user_id', name='token_user_id_key'),
    )
    # ### end Alembic commands ###
